services:
  - type: web
    name: akd-fashion-design
    env: python
    plan: free
    buildCommand: "bash ./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "achol-fashion-store.onrender.com,akd-fashion-design.onrender.com,akd.com,www.akd.com" # Specific Render service hostname
      - key: DATABASE_URL
        sync: false # Requires Neon Postgres string
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Requires Cloudinary keys
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DEBUG
        value: "False"
