# Generated by Django 4.2 on 2026-06-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productrecommendation_unique_recommendation_and_more'),
        ('orders', '0005_orderitem_vendor_orderitem_fulfillment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.productvariantvalue'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_selections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariantvalue'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_selections',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
