# Generated by Django 4.2 on 2026-06-09 14:22

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_variant_and_recommendation_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productrecommendation',
            name='unique_recommendation',
        ),
        migrations.RemoveConstraint(
            model_name='productvariantoption',
            name='unique_attribute_value',
        ),
        migrations.RenameIndex(
            model_name='productrecommendation',
            new_name='products_pr_source__ed4fda_idx',
            old_name='products_pr_source_idx',
        ),
        migrations.RenameIndex(
            model_name='productrecommendation',
            new_name='products_pr_relevan_8d7bad_idx',
            old_name='products_pr_relevanc_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariantvalue',
            new_name='products_pr_product_4ed1cf_idx',
            old_name='products_pr_product_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariantvalue',
            new_name='products_pr_sku_3af069_idx',
            old_name='products_pr_sku_idx',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), core.validators.validate_image_file]),
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together={('source_product', 'recommended_product', 'recommendation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariantoption',
            unique_together={('attribute', 'value')},
        ),
    ]
